"""
Matplotlib visualization utilities.
The code is designed to be hacky, and a lot of it is generated by AI.
"""

import functools
import typing as tp

import jax
import jax.numpy as jnp
import matplotlib as mpl
import matplotlib.animation as mpl_anim
import matplotlib.axes as mpl_ax
import matplotlib.figure as mpl_fig
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import gridspec
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

from exp_mpc.stewart_min import comp, mpc_spec, opt

################
# helper utils #
################


@functools.partial(jax.jit, static_argnames=["spec"])
def human_angle_vel(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Human angular velocity.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification (unused, kept for call-site consistency).

    Returns
    -------
    omega :
        The human angular velocity.
    """
    return ts.omega_head[0]


@functools.partial(jax.jit, static_argnames=["spec"])
def table_angle_vel(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Table angular velocity.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification (unused, kept for call-site consistency).

    Returns
    -------
    omega :
        The table angular velocity.
    """
    return comp.ang_vel(ts.y_quat[0], ts.y_quat[1], spec.dt)


@functools.partial(jax.jit, static_argnames=["spec"])
def human_angle_acc(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Human angular acceleration.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification (unused, kept for call-site consistency).

    Returns
    -------
    alpha :
        The human angular acceleration.
    """
    # off-by-one, which shouldn't be a big deal for visualization...
    # same comment applies to a lot of the functions here...
    return (ts.omega_head[1] - ts.omega_head[0]) / spec.dt


@functools.partial(jax.jit, static_argnames=["spec"])
def table_angle_acc(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Table angular acceleration.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification (unused, kept for call-site consistency).

    Returns
    -------
    alpha :
        The table angular acceleration.
    """
    q0 = ts.y_quat[0]
    q1 = ts.y_quat[1]
    q2 = ts.y_quat[2]
    ome0 = comp.ang_vel(q0, q1, spec.dt)
    ome1 = comp.ang_vel(q1, q2, spec.dt)
    return (ome1 - ome0) / spec.dt


@functools.partial(jax.jit, static_argnames=["spec"])
def table_angle(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Table angle.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification (unused, kept for call-site consistency).

    Returns
    -------
    rpy :
        The table roll, pitch, and yaw angles in degrees.
    """
    tilt = jnp.degrees(ts.euler_ang[0][:2])
    yaw = jnp.atleast_1d(jnp.degrees(ts.y_yaw[0]))
    return jnp.concatenate([tilt, yaw])


@functools.partial(jax.jit, static_argnames=["spec"])
def table_pos(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Table position.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification (unused, kept for call-site consistency).

    Returns
    -------
    pos :
        The table position as a 3-element array ``[x, y, z]``.
    """
    return ts.y_xyz[0]


@functools.partial(jax.jit, static_argnames=["spec"])
def table_vel(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Table velocity.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification (unused, kept for call-site consistency).

    Returns
    -------
    vel :
        The table velocity as a 3-element array ``[x_dot, y_dot, z_dot]``.
    """
    return (ts.y_xyz[1] - ts.y_xyz[0]) / spec.dt


@functools.partial(jax.jit, static_argnames=["spec"])
def table_acc(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Table acceleration.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification (unused, kept for call-site consistency).

    Returns
    -------
    acc :
        The table acceleration as a 3-element array
        ``[x_dot2, y_dot2, z_dot2]``.
    """
    vel0 = (ts.y_xyz[1] - ts.y_xyz[0]) / spec.dt
    vel1 = (ts.y_xyz[2] - ts.y_xyz[1]) / spec.dt
    return (vel1 - vel0) / spec.dt


@functools.partial(jax.jit, static_argnames=["spec"])
def human_vel(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Human velocity.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification used for rotation conventions.

    Returns
    -------
    vel :
        The human velocity as a 3-element array ``[x_dot, y_dot, z_dot]`` in the
        human frame.
    """
    I = np.eye(3)
    q0 = comp.inv_ty(ts.y_quat[0], ts.y_yaw[0])
    R0 = comp.rot(q0)
    q1 = comp.inv_ty(ts.y_quat[1], ts.y_yaw[1])
    R1 = comp.rot(q1)
    pos0 = ts.y_xyz[0] + (R0 - I) @ spec.human_displacement
    pos1 = ts.y_xyz[1] + (R1 - I) @ spec.human_displacement
    return R0.T @ (pos1 - pos0) / spec.dt


@functools.partial(jax.jit, static_argnames=["spec"])
def human_acc(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    """Human acceleration.

    Parameters
    ----------
    ts : opt.TrainState
        The train state containing the state and control trajectories.
    spec :
        MPC specification used for rotation conventions.

    Returns
    -------
    acc :
        The human acceleration as a 3-element array ``[x_dot2, y_dot2, z_dot2]``
        in the human frame.
    """
    I = np.eye(3)
    q0 = comp.inv_ty(ts.y_quat[0], ts.y_yaw[0])
    R0 = comp.rot(q0)
    q1 = comp.inv_ty(ts.y_quat[1], ts.y_yaw[1])
    R1 = comp.rot(q1)
    q2 = comp.inv_ty(ts.y_quat[2], ts.y_yaw[2])
    R2 = comp.rot(q2)
    pos0 = ts.y_xyz[0] + (R0 - I) @ spec.human_displacement
    pos1 = ts.y_xyz[1] + (R1 - I) @ spec.human_displacement
    pos2 = ts.y_xyz[2] + (R2 - I) @ spec.human_displacement
    return R0.T @ ((pos2 - 2.0 * pos1 + pos0) / spec.dt**2 + mpc_spec.gravity)


@jax.jit
def _table_pos(ts: opt.TrainState) -> jax.Array:
    xyz = ts.y_xyz[0]
    q = jnp.concatenate([ts.y_quat[0], jnp.array([0.0])])
    return jnp.concatenate([xyz, q])


@functools.partial(jax.jit, static_argnames=["spec"])
def _human_pos(ts: opt.TrainState, spec: mpc_spec.MPCSpec) -> jax.Array:
    q = comp.inv_ty(ts.y_quat[0], ts.y_yaw[0])
    R = comp.rot(q)
    I = np.eye(3)
    xyz = ts.y_xyz[0] + (R - I) @ spec.human_displacement
    return jnp.concatenate([xyz, q])


def _way_from_train(
    trajectory: list[opt.TrainState],
    spec: mpc_spec.MPCSpec,
) -> tuple[np.ndarray, np.ndarray]:
    """Convert train states to table and human waypoints."""
    table = np.array([_table_pos(ts) for ts in trajectory])
    human = np.array([_human_pos(ts, spec) for ts in trajectory])
    return table, human


#################
# visualization #
#################


def animate_trajectory(
    trajectory: list[opt.TrainState],
    limits: mpc_spec.MPCLimits,
    spec: mpc_spec.MPCSpec,
    sim_rate: float = 1.0,
    fps: float = 30.0,
    frame_range: tuple[int, int] | None = None,
) -> tuple[mpl_anim.FuncAnimation, mpl_fig.Figure]:
    """Animate Stewart platform motion over an MPC trajectory.

    Parameters
    ----------
    trajectory :
        Sequence of MPC train states.
        Each entry is one control cycle solution.
    spec :
        MPC specification, including geometry.
    sim_rate :
        Playback speed multiplier.
        ``1.0`` is nominal speed, ``2.0`` is twice as fast.
    fps :
        Animation frame rate.
    frame_range :
        Optional frame interval ``(start, stop)`` for partial playback.

    Returns
    -------
    anim :
        Matplotlib animation object.
    fig :
        Matplotlib figure used by the animation.

    See Also
    --------
    :func:`exp_mpc.stewart_min.mp_mpl.call_mp_animate_trajectory` :
        Helper function to call :func:`animate_trajectory` in a multi-threaded
        workflow.
        Namely, multiple ``frame_range`` parameters are scheduled on several
        cpus, and the resulting animations are concatenated into one video.
    """
    assert type(trajectory) is list
    assert len(trajectory) > 0
    # possible conversion needed
    if isinstance(trajectory[0], opt.TrainState):
        assert all(isinstance(ts, opt.TrainState) for ts in trajectory)
        table_waypoints, human_waypoints = _way_from_train(trajectory, spec)
    else:
        raise TypeError(
            "`animate_trajectory` now requires a list of `TrainState`."
        )

    # Setup figure
    fig = plt.figure(figsize=(16, 9))
    gs = gridspec.GridSpec(
        7,
        3,
        height_ratios=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6],
        width_ratios=[0.5, 1.0, 0.7],
        wspace=0.4,
        hspace=0.9,
    )

    # Control plots on the left
    control_axes = []
    ax1 = None
    for i in range(6):
        if i == 0:
            ax = fig.add_subplot(gs[i, 0])
            ax1 = ax
        else:
            ax = fig.add_subplot(gs[i, 0], sharex=ax1, sharey=ax1)
        control_axes.append(ax)
    control_lines = [ax.plot([], [], "b-")[0] for ax in control_axes]
    for i, ax in enumerate(control_axes):
        ax.set_title(f"u[{i}]")
        ax.grid(True)
        if i < 5:
            plt.setp(ax.get_xticklabels(), visible=False)

    control_axes[-1].set_xlabel("Horizon")
    control_abs = np.abs(
        np.concatenate([np.ravel(ts.control) for ts in trajectory])
    )
    control_lim = np.mean(control_abs) + np.std(control_abs) * 4.0
    # control_lim = np.max(control_abs)
    control_axes[-1].set_ylim(-control_lim, control_lim)
    control_axes[-1].set_xlim(0, trajectory[0].control.reshape(-1, 6).shape[0])
    fig.text(0.04, 0.5, "Control", va="center", rotation="vertical")

    # 3D plot for platform visualization
    ax_3d = fig.add_subplot(gs[:-1, 1], projection="3d")
    ax_3d.set_xlabel("X")
    ax_3d.set_ylabel("Y")
    ax_3d.set_zlabel("Z")  # type: ignore

    # Create a margin around the workspace
    x_lims = np.array(
        [point[0] for point in spec.bots] + [point[0] for point in spec.tops]
    )
    x_min = np.min(x_lims) - 0.5
    x_max = np.max(x_lims) + 0.5
    y_lims = np.array(
        [point[1] for point in spec.bots] + [point[1] for point in spec.tops]
    )
    y_min = np.min(y_lims) - 0.5
    y_max = np.max(y_lims) + 0.5
    z_lims = np.array(
        [point[2] for point in spec.bots] + [point[2] for point in spec.tops]
    )
    z_min = np.min(z_lims) - 0.5
    z_max = np.max(z_lims) + 1.0  # for extra height

    ax_3d.set_xlim(x_min, x_max)
    ax_3d.set_ylim(y_min, y_max)
    ax_3d.set_zlim(z_min, z_max)  # type: ignore

    # Plot the progression of time
    ax_time = fig.add_subplot(gs[-1, 1:])
    ax_time.set_xlabel("Progress")
    # ax_time.set_ylabel('Time')
    # ax_time.set_title('Trajectory Progress')
    ax_time.set_xlim(0, 1)
    ax_time.set_ylim(0, 1)
    ax_time.set_yticks([])  # Hide y-ticks for cleaner look
    ax_time.set_xticks([0, 0.25, 0.5, 0.75, 1.0])
    ax_time.set_xticklabels(["0%", "25%", "50%", "75%", "100%"])
    progress_bar = ax_time.barh(0.5, 0, height=0.3, color="blue", alpha=0.7)
    time_text = ax_time.text(0.02, 0.02, "", transform=ax_time.transAxes)

    # Plot for leg lengths
    ax_legs = fig.add_subplot(gs[:-1, 2])
    ax_legs.set_xlabel("Leg Number")
    ax_legs.set_ylabel("Length (m)")
    # ax_legs.set_title('Leg Lengths')
    ax_legs.set_xlim(0.5, 6.5)
    ax_legs.set_xticks(range(1, 7))
    ax_legs.set_ylim(limits.leg_min * 0.9, limits.leg_max * 1.1)
    ax_legs.axhline(
        y=limits.leg_min,
        color="r",
        linestyle="-",
        alpha=0.5,
        label="Min Length",
    )
    ax_legs.axhline(
        y=limits.leg_max,
        color="r",
        linestyle="-",
        alpha=0.5,
        label="Max Length",
    )

    # Initialize visualization elements
    (base_polygon,) = ax_3d.plot([], [], [], "ko-", linewidth=2, markersize=5)
    (platform_polygon,) = ax_3d.plot(
        [], [], [], "bo-", linewidth=2, markersize=5
    )
    legs = [ax_3d.plot([], [], [], "g-", linewidth=1)[0] for _ in range(6)]
    axis_length = 0.2
    head_axes = [
        ax_3d.plot([], [], [], "r-", linewidth=2)[0],
        ax_3d.plot([], [], [], "g-", linewidth=2)[0],
        ax_3d.plot([], [], [], "b-", linewidth=2)[0],
    ]
    leg_bars = ax_legs.bar(range(1, 7), [0] * 6, color="black", alpha=0.7)
    leg_text = ax_legs.text(
        0.02, 0.95, "", transform=ax_legs.transAxes, verticalalignment="top"
    )

    # Connect base points to form a polygon
    base_x = [spec.bots[i][0] for i in range(6)] + [spec.bots[0][0]]
    base_y = [spec.bots[i][1] for i in range(6)] + [spec.bots[0][1]]
    base_z = [spec.bots[i][2] for i in range(6)] + [spec.bots[0][2]]
    base_polygon.set_data(base_x, base_y)
    base_polygon.set_3d_properties(base_z)  # type: ignore

    # fig.tight_layout()

    # Interpolate trajectory for smoother animation
    num_points = len(trajectory)
    t_values = np.arange(0, num_points) * spec.dt
    t_interp = np.arange(
        0,
        spec.dt * num_points,
        1.0 / fps * sim_rate,
    )

    def interp_y(t, x, y):
        res = jax.vmap(jnp.interp, in_axes=[None, None, 1])(t, x, y)
        res = np.array(jnp.transpose(res))
        # need to re-normalize quaternion components
        res[:, 3:] /= np.tile(
            np.linalg.norm(res[:, 3:], axis=1).reshape(-1, 1), reps=(1, 4)
        )
        return np.array(res)

    interp_table = interp_y(t_interp, t_values, table_waypoints)
    interp_human = interp_y(t_interp, t_values, human_waypoints)
    assert interp_table.shape == interp_human.shape

    def update(i):
        if i >= interp_table.shape[0]:
            return

        # Update control plots
        sol_index = min(
            int(i * num_points / interp_table.shape[0]), num_points - 1
        )
        current_sol: opt.TrainState = trajectory[sol_index]
        u_horizon = current_sol.control.reshape(-1, 6)
        horizon_t = np.arange(u_horizon.shape[0])
        for j in range(6):
            control_lines[j].set_data(horizon_t, u_horizon[:, j])

        # Update platform position
        xyz_table = interp_table[i, :3]
        R_table = comp.rot(interp_table[i, 3:])
        delta = spec.human_displacement
        tops_world = [
            R_table @ (p - delta) + delta + xyz_table for p in spec.tops
        ]
        platform_x = [p[0] for p in tops_world] + [tops_world[0][0]]
        platform_y = [p[1] for p in tops_world] + [tops_world[0][1]]
        platform_z = [p[2] for p in tops_world] + [tops_world[0][2]]
        platform_polygon.set_data(platform_x, platform_y)
        platform_polygon.set_3d_properties(platform_z)  # type: ignore

        # Update head reference frame
        xyz_human = interp_human[i, :3]
        R_human = comp.rot(interp_human[i, 3:])
        head_pos = spec.human_displacement + xyz_human
        axis_dirs = R_human @ np.eye(3)
        for axis_line, axis_dir in zip(head_axes, axis_dirs.T):
            end_pos = head_pos + axis_length * axis_dir
            axis_line.set_data(
                [head_pos[0], end_pos[0]], [head_pos[1], end_pos[1]]
            )
            axis_line.set_3d_properties([head_pos[2], end_pos[2]])  # type: ignore

        # Update legs
        leg_lengths = []
        for j in range(6):
            start_point = spec.bots[j]
            end_point = tops_world[j]
            legs[j].set_data(
                [start_point[0], end_point[0]], [start_point[1], end_point[1]]
            )
            legs[j].set_3d_properties([start_point[2], end_point[2]])  # type: ignore

            # Compute leg length
            leg_vector = end_point - start_point
            leg_length = np.linalg.norm(leg_vector)
            leg_lengths.append(leg_length)

        # Update leg length bars
        for j, bar in enumerate(leg_bars):
            bar.set_height(leg_lengths[j])

            # Color the bar based on how close it is to limits
            if (
                leg_lengths[j] < limits.leg_min
                or leg_lengths[j] > limits.leg_max
            ):
                bar.set_color("red")
            else:
                bar.set_color("black")

        # Update leg length text
        x, y, z = xyz_table
        roll, pitch, yaw = comp.tilt2euler(interp_table[i, 3:6])
        leg_text.set_text(
            f"Position: ({x:.2f}, {y:.2f}, {z:.2f})\n"
            f"Orientation: ({np.degrees(roll):.2f}°, "
            f"{np.degrees(pitch):.2f}°, "
            f"{np.degrees(yaw):.2f}°)"
        )

        # Update progress bar
        progress = i / (interp_table.shape[0] - 1)
        progress_bar[0].set_width(progress)
        sim_time = i * len(trajectory) / interp_table.shape[0] * spec.dt
        sim_time_tot = (len(trajectory) - 1) * spec.dt
        time_text.set_text(f"Time: {sim_time:.1f}s / {sim_time_tot:.1f}s")

        return (
            platform_polygon,
            *legs,
            *head_axes,
            *leg_bars,
            leg_text,
            progress_bar[0],
            time_text,
            *control_lines,
        )

    frame_count = interp_table.shape[0]
    interval = 1e3 / fps  # convert to milliseconds

    anim_frames = frame_count
    if frame_range is not None:
        anim_frames = range(frame_range[0], frame_range[1])

    anim = mpl_anim.FuncAnimation(
        fig,
        update,  # type: ignore
        frames=anim_frames,
        interval=interval,
        blit=True,
        repeat=False,
        # repeat=True,
    )

    return anim, fig


def _get_limits(data: jax.Array) -> tuple[float, float]:
    """Get reasonable plotting limits for some data."""
    eps = 2**-4  # magic

    minimum = jnp.min(data)
    maximum = jnp.max(data)
    diff = maximum - minimum

    # edge case
    if minimum == 0.0 and maximum == 0.0:
        return (-0.2, 0.2)

    limit_diff = diff * eps
    limits = (
        float(minimum - limit_diff),
        float(maximum + limit_diff),
    )
    return limits


def _simple_plot(
    axis: mpl_ax.Axes,
    time: jax.Array,
    data: jax.Array,
    title: str,
    data_label: str,
    min_limit: float | None = None,
    max_limit: float | None = None,
    reference: jax.Array | None = None,
):
    axis.set_title(title)
    axis.set_ylabel(data_label)
    axis.set_xlabel("[s]")
    axis.plot(time, data, color="blue")
    if reference is not None:
        axis.plot(time, reference, color="orange", linestyle="--")
        data = jnp.concatenate([data, reference])
    if min_limit is not None:
        axis.axhline(y=min_limit, linestyle="-", alpha=0.5, color="red")
    if max_limit is not None:
        axis.axhline(y=max_limit, linestyle="-", alpha=0.5, color="red")
    axis.set_ylim(*_get_limits(data))
    axis.set_xlim(float(time[0]), float(time[-1]))
    axis.grid()


def _reference_helper(
    reference: jax.Array | None, index: int
) -> jax.Array | None:
    """Helper function to get the reference data for a specific axis."""
    if reference is None:
        return None
    if reference.ndim == 1:
        return reference
    if reference.ndim == 2 and reference.shape[1] == 3:
        return reference[:, index]
    raise ValueError(
        "Invalid reference shape. Must be 1D or 2D with shape (N, 3)."
    )


def _plot_cartesian_trajectory(
    axes: np.ndarray,
    trajectory: list[opt.TrainState],
    limits: mpc_spec.MPCLimits,
    spec: mpc_spec.MPCSpec,
    xyz_fun: tp.Callable[[opt.TrainState, mpc_spec.MPCSpec], jax.Array],
    angle_fun: tp.Callable[[opt.TrainState, mpc_spec.MPCSpec], jax.Array],
):
    """Common cartesian trajectory routines, for positions."""
    assert all(type(ax) is mpl_ax.Axes for ax in axes.flatten())
    assert len(trajectory) > 0
    times = jnp.arange(0, len(trajectory), dtype=float) * spec.dt

    ################
    # xyz position #
    ################

    # compute
    xyzs = jnp.array([xyz_fun(ts, spec) for ts in trajectory])

    # setup
    ax_x = axes[0, 0]
    ax_y = axes[0, 1]
    ax_z = axes[0, 2]

    # plot
    _simple_plot(
        axis=ax_x,
        time=times,
        data=xyzs[:, 0],
        title="X Position",
        data_label="[m]",
    )
    _simple_plot(
        axis=ax_y,
        time=times,
        data=xyzs[:, 1],
        title="Y Position",
        data_label="[m]",
    )
    _simple_plot(
        axis=ax_z,
        time=times,
        data=xyzs[:, 2],
        title="Z Position",
        data_label="[m]",
    )

    ####################
    # angular position #
    ####################

    # compute
    angles = jnp.array([angle_fun(ts, spec) for ts in trajectory])

    # setup
    ax_roll = axes[1, 0]
    ax_pitch = axes[1, 1]
    ax_yaw = axes[1, 2]

    # plot
    _simple_plot(
        axis=ax_roll,
        time=times,
        data=angles[:, 0],
        title="Roll Angle",
        data_label="[deg]",
        min_limit=-np.degrees(limits.max_roll),
        max_limit=np.degrees(limits.max_roll),
    )
    _simple_plot(
        axis=ax_pitch,
        time=times,
        data=angles[:, 1],
        title="Pitch Angle",
        data_label="[deg]",
        min_limit=-np.degrees(limits.max_pitch),
        max_limit=np.degrees(limits.max_pitch),
    )
    _simple_plot(
        axis=ax_yaw,
        time=times,
        data=angles[:, 2],
        title="Yaw Angle",
        data_label="[deg]",
        min_limit=-np.degrees(limits.max_yaw),
        max_limit=np.degrees(limits.max_yaw),
    )


def _plot_cartesian_trajectory_p(
    axes: np.ndarray,
    trajectory: list[opt.TrainState],
    limits: mpc_spec.MPCLimits,
    spec: mpc_spec.MPCSpec,
    xyz_vel_fun: tp.Callable[[opt.TrainState, mpc_spec.MPCSpec], jax.Array],
    angle_vel_fun: tp.Callable[[opt.TrainState, mpc_spec.MPCSpec], jax.Array],
    xyz_acc_fun: tp.Callable[[opt.TrainState, mpc_spec.MPCSpec], jax.Array],
    angle_acc_fun: tp.Callable[[opt.TrainState, mpc_spec.MPCSpec], jax.Array],
    references: dict[str, jax.Array] | None = None,
):
    """Common cartesian trajectory routines, for derivatives."""
    if references is None:
        references = {}
    assert all(type(ax) is mpl_ax.Axes for ax in axes.flatten())

    times = jnp.arange(0, len(trajectory), dtype=float) * spec.dt

    ################
    # xyz velocity #
    ################

    # compute
    xyz_vels = jnp.array([xyz_vel_fun(ts, spec) for ts in trajectory])

    # setup
    ax_x_vel = axes[0, 0]
    ax_y_vel = axes[0, 1]
    ax_z_vel = axes[0, 2]

    # plot
    _simple_plot(
        axis=ax_x_vel,
        time=times,
        data=xyz_vels[:, 0],
        title="X Velocity",
        data_label="[m/s]",
        min_limit=-limits.max_cart_vel,
        max_limit=limits.max_cart_vel,
    )
    _simple_plot(
        axis=ax_y_vel,
        time=times,
        data=xyz_vels[:, 1],
        title="Y Velocity",
        data_label="[m/s]",
        min_limit=-limits.max_cart_vel,
        max_limit=limits.max_cart_vel,
    )
    _simple_plot(
        axis=ax_z_vel,
        time=times,
        data=xyz_vels[:, 2],
        title="Z Velocity",
        data_label="[m/s]",
        min_limit=-limits.max_cart_vel,
        max_limit=limits.max_cart_vel,
    )

    ####################
    # angular velocity #
    ####################

    # compute
    angle_vels = jnp.array([angle_vel_fun(ts, spec) for ts in trajectory])

    # setup
    ax_omega_x_vel = axes[1, 0]
    ax_omega_y_vel = axes[1, 1]
    ax_omega_z_vel = axes[1, 2]

    # references?
    angle_vel_ref = None
    if "angular-velocity" in references:
        angle_vel_ref = jnp.rad2deg(references["angular-velocity"])

    # plot
    _simple_plot(
        axis=ax_omega_x_vel,
        time=times,
        data=jnp.rad2deg(angle_vels[:, 0]),
        title="X Angular Velocity",
        data_label="[deg/s]",
        min_limit=-jnp.rad2deg(limits.max_angle_vel),
        max_limit=jnp.rad2deg(limits.max_angle_vel),
        reference=_reference_helper(angle_vel_ref, 0),
    )
    _simple_plot(
        axis=ax_omega_y_vel,
        time=times,
        data=jnp.rad2deg(angle_vels[:, 1]),
        title="Y Angular Velocity",
        data_label="[deg/s]",
        min_limit=-jnp.rad2deg(limits.max_angle_vel),
        max_limit=jnp.rad2deg(limits.max_angle_vel),
        reference=_reference_helper(angle_vel_ref, 1),
    )
    _simple_plot(
        axis=ax_omega_z_vel,
        time=times,
        data=jnp.rad2deg(angle_vels[:, 2]),
        title="Z Angular Velocity",
        data_label="[deg/s]",
        min_limit=-jnp.rad2deg(limits.max_angle_vel),
        max_limit=jnp.rad2deg(limits.max_angle_vel),
        reference=_reference_helper(angle_vel_ref, 2),
    )

    ####################
    # xyz acceleration #
    ####################

    # compute
    xyz_accs = jnp.array([xyz_acc_fun(ts, spec) for ts in trajectory])

    # setup
    ax_x_acc = axes[2, 0]
    ax_y_acc = axes[2, 1]
    ax_z_acc = axes[2, 2]

    # references?
    xyz_acc_ref = None
    if "xyz-acceleration" in references:
        xyz_acc_ref = references["xyz-acceleration"]

    # plot
    _simple_plot(
        axis=ax_x_acc,
        time=times,
        data=xyz_accs[:, 0],
        title="X Acceleration",
        data_label="[m/s^2]",
        min_limit=-limits.max_cart_acc,
        max_limit=limits.max_cart_acc,
        reference=_reference_helper(xyz_acc_ref, 0),
    )
    _simple_plot(
        axis=ax_y_acc,
        time=times,
        data=xyz_accs[:, 1],
        title="Y Acceleration",
        data_label="[m/s^2]",
        min_limit=-limits.max_cart_acc,
        max_limit=limits.max_cart_acc,
        reference=_reference_helper(xyz_acc_ref, 1),
    )
    _simple_plot(
        axis=ax_z_acc,
        time=times,
        data=xyz_accs[:, 2],
        title="Z Acceleration",
        data_label="[m/s^2]",
        min_limit=-limits.max_cart_acc,
        max_limit=limits.max_cart_acc,
        reference=_reference_helper(xyz_acc_ref, 2),
    )

    ########################
    # angular acceleration #
    ########################

    # compute
    angle_accs = jnp.array([angle_acc_fun(ts, spec) for ts in trajectory])

    # setup
    ax_omega_x_acc = axes[3, 0]
    ax_omega_y_acc = axes[3, 1]
    ax_omega_z_acc = axes[3, 2]

    # plot
    _simple_plot(
        axis=ax_omega_x_acc,
        time=times,
        data=jnp.rad2deg(angle_accs[:, 0]),
        title="X Angular Acceleration",
        data_label="[deg/s^2]",
        min_limit=-jnp.rad2deg(limits.max_angle_acc),
        max_limit=jnp.rad2deg(limits.max_angle_acc),
    )
    _simple_plot(
        axis=ax_omega_y_acc,
        time=times,
        data=jnp.rad2deg(angle_accs[:, 1]),
        title="Y Angular Acceleration",
        data_label="[deg/s^2]",
        min_limit=-jnp.rad2deg(limits.max_angle_acc),
        max_limit=jnp.rad2deg(limits.max_angle_acc),
    )
    _simple_plot(
        axis=ax_omega_z_acc,
        time=times,
        data=jnp.rad2deg(angle_accs[:, 2]),
        title="Z Angular Acceleration",
        data_label="[deg/s^2]",
        min_limit=-jnp.rad2deg(limits.max_angle_acc),
        max_limit=jnp.rad2deg(limits.max_angle_acc),
    )


def plot_human_trajectory(
    trajectory: list[opt.TrainState],
    limits: mpc_spec.MPCLimits,
    spec: mpc_spec.MPCSpec,
    references: dict[str, jax.Array] | None = None,
    fig_title: str = "Head Trajectory",
    fig_kwds: dict | None = None,
) -> mpl_fig.Figure:
    """Plot head velocities and accelerations over an MPC trajectory.

    Parameters
    ----------
    trajectory :
        Sequence of MPC train states.
    limits :
        MPC limits, used for limit lines.
    spec :
        MPC specification, used for timing.
    references :
        Optional reference signals.
        Supported keys are ``"xyz-acceleration"`` and
        ``"angular-velocity"``.
    fig_title :
        Figure super title.
    fig_kwds :
        Extra keyword arguments passed to :func:`matplotlib.pyplot.subplots`.

    Returns
    -------
    fig :
        Figure with 12 subplots for linear velocity, angular velocity, linear
        acceleration, and angular acceleration.
    """
    # setup
    if fig_kwds is None:
        fig_kwds = {}
    if references is None:
        references = {}
    gridspec_kw = {
        # "height_ratios": [1.0, 1.0, 1.0, 1.0],
        # "width_ratios": [1.0, 1.0, 1.0],
        "wspace": 0.35,
        "hspace": 0.7,
    }
    fig, axes = plt.subplots(
        nrows=4, ncols=3, gridspec_kw=gridspec_kw, figsize=(16, 10), **fig_kwds
    )
    fig.suptitle(fig_title, fontsize=16)
    _plot_cartesian_trajectory_p(
        axes=axes,
        trajectory=trajectory,
        limits=limits,
        spec=spec,
        xyz_vel_fun=human_vel,
        angle_vel_fun=human_angle_vel,
        xyz_acc_fun=human_acc,
        angle_acc_fun=human_angle_acc,
        references=references,
    )
    return fig


def plot_vestibular_trajectory(
    trajectory: list[opt.TrainState],
    limits: mpc_spec.MPCLimits,
    spec: mpc_spec.MPCSpec,
    fig_title: str = "Vestibular Trajectory",
    fig_kwds: dict | None = None,
) -> mpl_fig.Figure:
    """Plot vestibular outputs for irl and simulated over an MPC trajectory.

    Parameters
    ----------
    trajectory :
        Sequence of MPC train states.
    limits :
        MPC limits, used for plot limits.
    spec :
        MPC specification, used for time axis spacing.
    fig_title :
        Figure super title.
    fig_kwds :
        Extra keyword arguments passed to :func:`matplotlib.pyplot.subplots`.

    Returns
    -------
    fig :
        Figure with angular velocity and linear acceleration panels.
        Each panel includes the irl signal and the simulated reference signal.
    """
    #########
    # setup #
    #########

    if fig_kwds is None:
        fig_kwds = {}
    gridspec_kw = {
        # "height_ratios": [1.0, 1.0, 1.0, 1.0],
        # "width_ratios": [1.0, 1.0, 1.0],
        "wspace": 0.35,
        "hspace": 0.35,
    }
    fig, axes = plt.subplots(
        nrows=2, ncols=3, gridspec_kw=gridspec_kw, figsize=(16, 8), **fig_kwds
    )
    fig.suptitle(fig_title, fontsize=16)

    times = jnp.arange(0, len(trajectory), dtype=float) * spec.dt

    ####################
    # angular velocity #
    ####################

    # compute
    @jax.jit
    def get_omegas(ts: opt.TrainState) -> tuple[jax.Array, jax.Array]:
        return ts.y_vest_irl[0, 3:], ts.y_vest_sim[0, 3:]

    omegas = jnp.array([get_omegas(ts)[0] for ts in trajectory])
    omegas_ref = jnp.array([get_omegas(ts)[1] for ts in trajectory])

    # plot
    _simple_plot(
        axis=axes[0, 0],
        time=times,
        data=jnp.rad2deg(omegas[:, 0]),
        title="X Angular Velocity",
        data_label="[deg/s]",
        min_limit=-jnp.rad2deg(limits.max_angle_vel),
        max_limit=jnp.rad2deg(limits.max_angle_vel),
        reference=jnp.rad2deg(omegas_ref[:, 0]),
    )
    _simple_plot(
        axis=axes[0, 1],
        time=times,
        data=jnp.rad2deg(omegas[:, 1]),
        title="Y Angular Velocity",
        data_label="[deg/s]",
        min_limit=-jnp.rad2deg(limits.max_angle_vel),
        max_limit=jnp.rad2deg(limits.max_angle_vel),
        reference=jnp.rad2deg(omegas_ref[:, 1]),
    )
    _simple_plot(
        axis=axes[0, 2],
        time=times,
        data=jnp.rad2deg(omegas[:, 2]),
        title="Z Angular Velocity",
        data_label="[deg/s]",
        min_limit=-jnp.rad2deg(limits.max_angle_vel),
        max_limit=jnp.rad2deg(limits.max_angle_vel),
        reference=jnp.rad2deg(omegas_ref[:, 2]),
    )

    #######################
    # linear acceleration #
    #######################

    # compute
    @jax.jit
    def get_lin_dyn(ts: opt.TrainState) -> tuple[jax.Array, jax.Array]:
        return ts.y_vest_irl[0, :3], ts.y_vest_sim[0, :3]

    lin_dyn = jnp.array([get_lin_dyn(ts)[0] for ts in trajectory])
    lin_dyn_ref = jnp.array([get_lin_dyn(ts)[1] for ts in trajectory])

    # plot
    _simple_plot(
        axis=axes[1, 0],
        time=times,
        data=lin_dyn[:, 0],
        title="X Linear Acceleration",
        data_label="[m/s^2]",
        min_limit=-limits.max_cart_acc,
        max_limit=limits.max_cart_acc,
        reference=lin_dyn_ref[:, 0],
    )
    _simple_plot(
        axis=axes[1, 1],
        time=times,
        data=lin_dyn[:, 1],
        title="Y Linear Acceleration",
        data_label="[m/s^2]",
        min_limit=-limits.max_cart_acc,
        max_limit=limits.max_cart_acc,
        reference=lin_dyn_ref[:, 1],
    )
    _simple_plot(
        axis=axes[1, 2],
        time=times,
        data=lin_dyn[:, 2],
        title="Z Linear Jerk",
        data_label="[m/s^2]",
        min_limit=-limits.max_cart_acc,
        max_limit=limits.max_cart_acc,
        reference=lin_dyn_ref[:, 2],
    )

    return fig


def plot_cartesian_table_trajectory(
    trajectory: list[opt.TrainState],
    limits: mpc_spec.MPCLimits,
    spec: mpc_spec.MPCSpec,
    fig_title: str = "Table Trajectory",
    fig_kwds: dict | None = None,
) -> mpl_fig.Figure:
    """Plot table pose and derivatives over an MPC trajectory.

    Parameters
    ----------
    trajectory :
        Sequence of MPC train states.
    limits :
        MPC limits, used for limit lines.
    spec :
        MPC specification, used for time axis spacing.
    fig_title :
        Figure super title.
    fig_kwds :
        Extra keyword arguments passed to :func:`matplotlib.pyplot.subplots`.

    Returns
    -------
    fig :
        Figure with 18 subplots for
        table position, table angles, and first and second derivatives.
    """
    if fig_kwds is None:
        fig_kwds = {}
    gs_kwds = {
        # "height_ratios": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        # "width_ratios": [1.0, 1.0, 1.0],
        "wspace": 0.35,
        "hspace": 1.0,
    }
    fig, axes = plt.subplots(
        nrows=6, ncols=3, gridspec_kw=gs_kwds, figsize=(16, 10), **fig_kwds
    )
    fig.suptitle(fig_title, fontsize=16)
    _plot_cartesian_trajectory(
        axes=axes[:2, :],
        trajectory=trajectory,
        xyz_fun=table_pos,
        angle_fun=table_angle,
        limits=limits,
        spec=spec,
    )
    _plot_cartesian_trajectory_p(
        axes=axes[2:, :],
        trajectory=trajectory,
        xyz_vel_fun=table_vel,
        angle_vel_fun=table_angle_vel,
        xyz_acc_fun=table_acc,
        angle_acc_fun=table_angle_acc,
        limits=limits,
        spec=spec,
    )
    return fig


def plot_actuator_trajectory(
    trajectory: list[opt.TrainState],
    limits: mpc_spec.MPCLimits,
    spec: mpc_spec.MPCSpec,
    use_estop: bool = False,
    fig_title: str = "Actuator Trajectory",
    fig_kwds: dict | None = None,
) -> mpl_fig.Figure:
    """Plot actuator state summaries over an MPC trajectory.

    The figure includes leg length, leg velocity, leg acceleration,
    and top and bottom joint angles.

    Parameters
    ----------
    trajectory :
        Sequence of MPC train states.
    limits :
        MPC limits, used for actuator limit lines.
    spec :
        MPC specification, used for timing and geometry.
    use_estop :
        True to use estop variants.
    fig_title :
        Figure super title.
    fig_kwds :
        Extra keyword arguments passed to :func:`matplotlib.pyplot.subplots`.

    Returns
    -------
    fig :
        Figure with actuator length, velocity, acceleration, and joint-angle
        trajectories.
    """
    if fig_kwds is None:
        fig_kwds = {}
    fig, axes = plt.subplots(
        nrows=2,
        ncols=2,
        figsize=(16, 10),
        gridspec_kw={"wspace": 0.35},
        **fig_kwds,
    )
    fig.suptitle(fig_title, fontsize=16)

    times = np.arange(0, len(trajectory), dtype=float) * spec.dt

    colors = [mpl.colormaps["viridis"](c) for c in np.linspace(0, 1, 6)]

    ###############
    # leg lengths #
    ###############

    if not use_estop:
        leg_pos_vals = np.array([ts.leg_pos[0] for ts in trajectory])
        leg_pos_title = "Leg Lengths"
    else:
        leg_pos_vals = np.array([ts.leg_pos_estop[0] for ts in trajectory])
        leg_pos_title = "Leg Lengths Estop"

    ax_pos = axes[0, 0]
    ax_pos.set_title(leg_pos_title)
    ax_pos.set_xlabel("[s]")
    ax_pos.set_ylabel("[m]")
    ax_pos.set_xlim(times[0], times[-1])
    ax_pos.set_ylim(*_get_limits(leg_pos_vals))
    ax_pos.grid()

    for leg_num, color in zip(range(leg_pos_vals.shape[1]), colors):
        ax_pos.plot(
            times,
            leg_pos_vals[:, leg_num],
            color=color,
            label=f"Leg {leg_num + 1}",
        )
    ax_pos.axhline(
        y=limits.leg_min,
        linestyle="-",
        alpha=0.5,
        color="red",
        label="Min Length",
    )
    ax_pos.axhline(
        y=limits.leg_max,
        linestyle="-",
        alpha=0.5,
        color="red",
        label="Max Length",
    )
    ax_pos.legend()

    ##################
    # leg velocities #
    ##################

    leg_vel_vals = np.array([ts.leg_vel[0] for ts in trajectory])

    ax_vel = axes[0, 1]
    ax_vel.set_title("Leg Velocities")
    ax_vel.set_xlabel("[s]")
    ax_vel.set_ylabel("[m/s]")
    ax_vel.set_xlim(times[0], times[-1])
    ax_vel.set_ylim(*_get_limits(leg_vel_vals))
    ax_vel.grid()

    for leg_num, color in zip(range(leg_vel_vals.shape[1]), colors):
        ax_vel.plot(
            times,
            leg_vel_vals[:, leg_num],
            color=color,
            label=f"Leg {leg_num + 1}",
        )
    ax_vel.axhline(
        y=-limits.max_leg_vel,
        linestyle="-",
        alpha=0.5,
        color="red",
        label="Min Velocity",
    )
    ax_vel.axhline(
        y=limits.max_leg_vel,
        linestyle="-",
        alpha=0.5,
        color="red",
        label="Max Velocity",
    )
    ax_vel.legend()

    #####################
    # leg accelerations #
    #####################

    leg_acc_vals = np.array(
        [(ts.leg_vel[1] - ts.leg_vel[0]) / spec.dt for ts in trajectory]
    )

    ax_acc = axes[1, 0]
    ax_acc.set_title("Leg Accelerations")
    ax_acc.set_xlabel("[s]")
    ax_acc.set_ylabel("[m/s^2]")
    ax_acc.set_xlim(times[0], times[-1])
    ax_acc.set_ylim(*_get_limits(leg_acc_vals))
    ax_acc.grid()

    for leg_num, color in zip(range(leg_acc_vals.shape[1]), colors):
        ax_acc.plot(
            times,
            leg_acc_vals[:, leg_num],
            color=color,
            label=f"Leg {leg_num + 1}",
        )
    ax_acc.legend()

    ################
    # joint angles #
    ################

    top_joint_angles = np.degrees(
        np.array([ts.leg_ang[0, :6] for ts in trajectory])
    )

    bot_joint_angles = np.degrees(
        np.array([ts.leg_ang[0, 6:] for ts in trajectory])
    )

    ax_angles = axes[1, 1]
    ax_angles.set_title("Joint Angles")
    ax_angles.set_xlabel("[s]")
    ax_angles.set_ylabel("[deg]")
    ax_angles.set_xlim(times[0], times[-1])
    y_lim_data = jnp.concatenate(
        [top_joint_angles.flatten(), bot_joint_angles.flatten()]
    )
    ax_angles.set_ylim(*_get_limits(y_lim_data))
    ax_angles.grid()

    joint_colors = [mpl.colormaps["viridis"](c) for c in np.linspace(0, 1, 12)]

    for leg_num, color in zip(
        range(top_joint_angles.shape[1]), joint_colors[:6]
    ):
        ax_angles.plot(
            times,
            top_joint_angles[:, leg_num],
            color=color,
            label=f"Top Joint {leg_num + 1}",
        )
    for leg_num, color in zip(
        range(bot_joint_angles.shape[1]), joint_colors[6:]
    ):
        ax_angles.plot(
            times,
            bot_joint_angles[:, leg_num],
            color=color,
            label=f"Bottom Joint {leg_num + 1}",
        )
    ax_angles.axhline(
        y=np.degrees(limits.joint_max_angle),
        linestyle="-",
        alpha=0.5,
        color="red",
        label="Max Joint Angle",
    )
    ax_angles.legend()

    return fig
